services:
  db:
    image: postgres:16
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5439:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
 #тестовая база для написания тестов к эндпоинтам     
  test_db:
    image: postgres:16
    container_name: test_task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5440:5432"
    volumes:
      - ./test_postgresdata:/var/lib/postgresql/data